name = "opentoken"
description = "facility for performing token analysis and parsing within Ada"
version = "6.0.3"

authors = ["Stephen Leake"]
maintainers = ["Lionel Draghi <lionel.draghi@free.fr>"]
maintainers-logins = ["LionelDraghi"]
licenses = "GPL-3.0-or-later"
website = ""
tags = ["lexer", "parser"]

project-files = ["./build/release/opentoken_lib.gpr"]

[[depends-on]]
